### ISSUE TITLE
adding repository field in package.json so there will be link from npmjs.com to here

### ISSUE THREAD

**Issue by oriSomething** [vjeux/download-file-sync#2]
Look at the title :arrow_up:

**Comment by vjeux** [comment]
Can you send a pull request? :)

**Comment by oriSomething** [comment]
done :)
only needs you to publish that to npm after merge

**Comment by vjeux** [comment]
merged and published, thanks!

**Comment by oriSomething** [comment]
that's weird... i don't see the link on npm :/ maybe it's cache? because it worked to me in another repo

**Comment by oriSomething** [comment]
okay... i see it when `npm info download-file-sync`

**Comment by vjeux** [comment]
It's there now: https://www.npmjs.com/package/download-file-sync
